"""create sentiment_snapshots

Revision ID: 8b6bfc75d531
Revises: b46d83518d0d
Create Date: 2026-05-29 00:31:15.030387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b6bfc75d531'
down_revision: Union[str, None] = 'b46d83518d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiment_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('sentiment_label', sa.String(length=20), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('headline_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=False),
    sa.Column('source_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_snapshots_ticker'), 'sentiment_snapshots', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_snapshots_ticker'), table_name='sentiment_snapshots')
    op.drop_table('sentiment_snapshots')
    # ### end Alembic commands ###
